embeddings:
  per_signal_overrides:
    actuator:
      summary-power_nbi:
        encoder_name: dct3d
        encoder_kwargs:
          keep_h: 1
          keep_w: 1
          keep_t: 8
    output:
      pf_active-coil_current:
        encoder_name: dct3d
        encoder_kwargs:
          keep_h: 10
          keep_w: 1
          keep_t: 1
      pf_active-solenoid_current:
        encoder_name: dct3d
        encoder_kwargs:
          keep_h: 1
          keep_w: 1
          keep_t: 2
