embeddings:
  per_signal_overrides:
    input:
      pf_active-coil_current:
        encoder_name: vae
        encoder_kwargs:
          model_dir: conv1d_vae_config_coil_current
          device:
    output:
      pf_active-coil_current:
        encoder_name: vae
        encoder_kwargs:
          model_dir: conv1d_vae_config_coil_current
#          device:
