embeddings:
  per_signal_overrides:
    output:
      equilibrium-psi:
        encoder_name: dct3d
        encoder_kwargs:
          selection_mode: rank
          coeff_indices_path: dct3d_indices/output_equilibrium-psi.npy
          coeff_shape:
          - 65
          - 65
          - 5
          num_coeffs: 233
          explained_energy: 0.9990052455507312
          dim_distribution:
            unique_h: 18
            unique_w: 25
            unique_t: 5
