embeddings:
  per_signal_overrides:
    output:
      summary-ip:
        encoder_name: dct3d
        encoder_kwargs:
          selection_mode: rank
          coeff_indices_path: dct3d_indices/output_summary-ip.npy
          coeff_shape:
          - 1
          - 1
          - 400
          num_coeffs: 24
          explained_energy: 0.9990360241901731
          dim_distribution:
            unique_h: 1
            unique_w: 1
            unique_t: 24
