experiment_base: "scripts_mast/configs/task_2-1/experiment_base.yaml"
embedding_config: "scripts_mast/configs/task_2-1/embeddings_default.yaml"
phase: eval
eval_id: eval_test

# Required: which trained run to evaluate
model_init:
  model_dir: "runs/test/"


data:
  cache:
    enable: true
    num_workers: 4
  keep_output_native: true


preprocess:
  valid_windows:
    min_valid_inputs_actuators: 1
    min_valid_outputs: 1
    min_valid_chunks: 1
    window_stride_sec: 0.005


loader:
  batch_size: 1024
  num_workers: 1
  drop_last: false
  batches_per_epoch: null   # ignored in evaluation


eval:
  # list of inputs/actuators/outputs you want to drop for evaluation
  # null: evaluate the full model
  drop:
    inputs: # ["pf_active-coil_current"]
    actuators:
    outputs: # ["pf_active-solenoid_current", "summary-ip"]

  metrics:
    enable: true

  traces:
    enable: true
    n_max: 2
    signals: ["pf_active-coil_current"]           # null → save all outputs
    times_indexes: [0, 1]                         # null → save full horizon