# Default configuration for EVAL phase.
#
# Model to evaluate is now specified via CLI: --model <run_id_or_path>
#
# Outputs are automatically saved under:
#   runs/<model_id>/eval/

seed: 54

runtime:
  debug_logging: false

data:
  local: false         # True = uses local dataset, False = HPC / remote
  subset_of_shots: 10   # None / null → uses all shots

  keep_output_native: true
  cache:
    enable: true
    dtype: float16          # or float32; default behavior if omitted is “no cast”
    num_workers: 32
    max_windows:
      train: null
      val: null


preprocess:
  valid_windows:
    min_valid_inputs_actuators: 1
    min_valid_outputs: 1
    min_valid_chunks: 1
    window_stride_sec: null  # if null we evaluate on all the possible windows


loader:
  batch_size: 512
  num_workers: 0
  drop_last: false


eval:
  # list of inputs/actuators/outputs you want to drop for evaluation
  # null: evaluate the full model

  amp:
    enable: true

  drop:
    inputs: null # ["pf_active-coil_current"]
    actuators: null
    outputs: null # ["pf_active-solenoid_current", "summary-ip"]

  compute_metrics:
    per_task: true
    per_window: false
    per_timestamp: false

  traces:
    enable: false
    n_max: 2
    signals: null # ["pf_active-coil_current"]      # null → save all outputs
    times_indexes: # [0, 1]                         # null → save full horizon