
task_name: _test

sources_and_signals:
  input_name: &input_keys
    - - pf_active
      - coil_current
    - - pf_active
      - solenoid_current
    - - summary
      - ip

  actuator_name: &actuator_keys
    - - pf_active
      - coil_voltage
    - - summary
      - power_nbi

  output_name: &output_keys
#    - - pf_active
#      - coil_current
#    - - pf_active
#      - solenoid_current
#    - - summary
#      - ip
    - - equilibrium
      - psi
    - - thomson_scattering
      - n_e
    - - thomson_scattering
      - t_e
    - - soft_x_rays
      - horizontal_cam_lower

task_window_segmenter:
  input_keys: *input_keys
  actuator_keys: *actuator_keys
  output_keys: *output_keys
  input_length: 0.005
  output_length: 0.025
  delta: 0 # this is forecasting
  verbose: false

stride_window: 0.001