embeddings:
  per_signal_overrides:
    output:
      thomson_scattering-t_e:
        encoder_name: dct3d
        encoder_kwargs:
          selection_mode: rank
          coeff_indices_path: dct3d_indices/output_thomson_scattering-t_e.npy
          coeff_shape:
          - 120
          - 1
          - 1
          num_coeffs: 111
          explained_energy: 0.9990054568580837
          dim_distribution:
            unique_h: 111
            unique_w: 1
            unique_t: 1
      thomson_scattering-n_e:
        encoder_name: dct3d
        encoder_kwargs:
          selection_mode: rank
          coeff_indices_path: dct3d_indices/output_thomson_scattering-n_e.npy
          coeff_shape:
          - 120
          - 1
          - 1
          num_coeffs: 109
          explained_energy: 0.9990929843559561
          dim_distribution:
            unique_h: 109
            unique_w: 1
            unique_t: 1
      equilibrium-beta_tor:
        encoder_name: dct3d
        encoder_kwargs:
          selection_mode: rank
          coeff_indices_path: dct3d_indices/output_equilibrium-beta_tor.npy
          coeff_shape:
          - 1
          - 1
          - 1
          num_coeffs: 1
          explained_energy: 1.0
          dim_distribution:
            unique_h: 1
            unique_w: 1
            unique_t: 1
      equilibrium-beta_pol:
        encoder_name: dct3d
        encoder_kwargs:
          selection_mode: rank
          coeff_indices_path: dct3d_indices/output_equilibrium-beta_pol.npy
          coeff_shape:
          - 1
          - 1
          - 1
          num_coeffs: 1
          explained_energy: 1.0
          dim_distribution:
            unique_h: 1
            unique_w: 1
            unique_t: 1
      equilibrium-beta_normal:
        encoder_name: dct3d
        encoder_kwargs:
          selection_mode: rank
          coeff_indices_path: dct3d_indices/output_equilibrium-beta_normal.npy
          coeff_shape:
          - 1
          - 1
          - 1
          num_coeffs: 1
          explained_energy: 1.0
          dim_distribution:
            unique_h: 1
            unique_w: 1
            unique_t: 1
