"""
Configuration loading utilities for the Multi-Modal Transformer (MMT) project.

This loader follows a convention-based config layout (no pointers inside YAML):

scripts_mast/configs/
  common/
    core.yaml
    embeddings.yaml
    finetune.yaml
    pretrain.yaml
    eval.yaml
    tune_dct3d.yaml
  tasks/
    <task>/
      task.yaml
      finetune_overrides.yaml        (optional)
      pretrain_overrides.yaml        (optional)
      eval_overrides.yaml            (optional)
      tune_dct3d_overrides.yaml      (optional)
      embeddings_overrides.yaml      (optional, generated by tuning)

Merge order (later wins):
  1) common/core.yaml
  2) common/embeddings.yaml
  3) common/<phase>.yaml
  4) tasks/<task>/task.yaml
  5) tasks/<task>/<phase>_overrides.yaml (optional)
  6) tasks/<task>/embeddings_overrides.yaml (optional; included by default for
     pretrain/finetune/eval, NOT included for tune_dct3d)

NOTE
----
Dataset-specific task config resolution is intentionally NOT handled here.
The integration layer (scripts_mast/) resolves task_config and signals.

Paths behavior
--------------
• pretrain / finetune:
    - run_dir = <repo_root>/runs/<run_id>
    - saves config_merged.yaml into run_dir

• eval:
    - requires model_init.model_dir (training run directory)
    - run_dir = <model_dir>/<eval_id>
    - saves config_merged.yaml into run_dir

• tune_dct3d:
    - run_dir = <configs_root>/tasks/<task>
    - does NOT save config_merged.yaml (primary artifact is embeddings_overrides.yaml)
"""

from __future__ import annotations

import copy
import datetime
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict

import yaml

from mmt.utils.paths import get_repo_root


# ---------------------------------------------------------------------------
# YAML helpers
# ---------------------------------------------------------------------------


def _load_yaml(path: Path) -> Dict[str, Any]:
    with path.open("r", encoding="utf-8") as f:
        return yaml.safe_load(f) or {}


def _deep_merge(base: Dict[str, Any], override: Dict[str, Any]) -> Dict[str, Any]:
    """
    Recursively merge two dictionaries.

    - Dict values are merged recursively
    - Non-dict values are replaced
    - Lists are replaced (not concatenated)
    """
    merged = copy.deepcopy(base)
    for k, v in override.items():
        if k in merged and isinstance(merged[k], dict) and isinstance(v, dict):
            merged[k] = _deep_merge(merged[k], v)
        else:
            merged[k] = copy.deepcopy(v)
    return merged


# ---------------------------------------------------------------------------
# Path resolution
# ---------------------------------------------------------------------------


def _resolve_from_repo_root(path_str: str) -> Path:
    """
    Resolve a path relative to the repository root.

    Rules:
      • absolute paths are returned unchanged
      • paths beginning with "mmt/" map to <repo_root>/src/mmt/...
      • all other relative paths are resolved under <repo_root>
    """
    p = Path(path_str)
    if p.is_absolute():
        return p

    repo_root = get_repo_root()

    if p.parts and p.parts[0] == "mmt":
        return (repo_root / "src" / p).resolve()

    return (repo_root / p).resolve()


# ---------------------------------------------------------------------------
# Paths computation
# ---------------------------------------------------------------------------


def _compute_paths(
    merged: Dict[str, Any], *, configs_root: Path, task_dir: Path
) -> Dict[str, str]:
    """
    Compute repo/run paths depending on phase.
    """
    repo_root = get_repo_root()
    global_runs_root = repo_root / "runs"

    phase = merged.get("phase")
    if phase is None:
        raise ValueError("Missing required argument: phase.")

    task = merged.get("task", "unknown_task")
    timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")

    # ----------------------------------------------------------
    # TUNING PHASE: tune_dct3d (no runs/, write near task config)
    # ----------------------------------------------------------
    if phase == "tune_dct3d":
        task_dir = task_dir.resolve()
        task_dir.mkdir(parents=True, exist_ok=True)
        return {
            "repo_root": str(repo_root),
            "configs_root": str(configs_root),
            "run_dir": str(task_dir),
            "config_dir": str(task_dir),
        }

    # ----------------------------------------------------------
    # TRAINING PHASE: pretrain or finetune
    # ----------------------------------------------------------
    if phase in ("pretrain", "finetune"):
        run_id = merged.get("run_id") or f"{task}__{phase}__{timestamp}"
        run_dir = global_runs_root / run_id
        run_dir.mkdir(parents=True, exist_ok=True)
        return {
            "repo_root": str(repo_root),
            "runs_root": str(global_runs_root),
            "run_dir": str(run_dir),
        }

    # ----------------------------------------------------------
    # EVALUATION PHASE
    # ----------------------------------------------------------
    if phase == "eval":
        init_cfg = merged.get("model_init", {})
        model_dir = init_cfg.get("model_dir")
        if model_dir is None:
            raise ValueError(
                "Eval phase requires model_init.model_dir pointing to a training run."
            )

        model_dir = _resolve_from_repo_root(str(model_dir))
        if not model_dir.exists():
            raise FileNotFoundError(f"Training run directory not found: {model_dir}")

        eval_id = merged.get("eval_id") or f"eval__{timestamp}"
        eval_dir = model_dir / eval_id
        eval_dir.mkdir(parents=True, exist_ok=True)

        return {
            "repo_root": str(repo_root),
            "runs_root": str(model_dir),
            "run_dir": str(eval_dir),
            "eval_dir": str(eval_dir),
        }

    raise ValueError(f"Unsupported phase: {phase}")


# ---------------------------------------------------------------------------
# Dynamic ExperimentConfig
# ---------------------------------------------------------------------------


@dataclass
class ExperimentConfig:
    """
    Dynamic configuration object.

    Every top-level key in the merged YAML dictionary is available
    as an attribute: cfg.model, cfg.preprocess, cfg.loader, etc.

    The full merged dictionary is stored in cfg.raw.
    """

    raw: Dict[str, Any]

    def __getattr__(self, key: str) -> Any:
        if key in self.raw:
            return self.raw[key]
        raise AttributeError(f"'ExperimentConfig' has no attribute '{key}'")

    def get(self, key: str, default=None):
        return self.raw.get(key, default)


# ---------------------------------------------------------------------------
# Main loader
# ---------------------------------------------------------------------------


def load_experiment_config(
    *,
    task: str,
    phase: str,
    configs_root: str | Path = "scripts_mast/configs",
    run_id: str | None = None,
    eval_id: str | None = None,
    use_embeddings_overrides: bool = True,
) -> ExperimentConfig:
    """
    Load and merge an experiment configuration using the convention-based layout.

    Parameters
    ----------
    task:
        Task name = folder name under <configs_root>/tasks/<task>/.

    phase:
        One of: pretrain, finetune, eval, tune_dct3d.

    configs_root:
        Root config directory (default: scripts_mast/configs).

    run_id:
        Optional run_id for training phases. If omitted, a timestamped id is used.

    eval_id:
        Optional eval_id for eval. If omitted, eval__<timestamp> is used.

    use_embeddings_overrides:
        If True, and tasks/<task>/embeddings_overrides.yaml exists, merge it for
        pretrain/finetune/eval. For tune_dct3d, existing overrides are NOT merged.

    Returns
    -------
    ExperimentConfig
        Dynamic config object exposing top-level keys as attributes and also storing
        the full merged dictionary in cfg.raw.
    """
    if phase not in ("pretrain", "finetune", "eval", "tune_dct3d"):
        raise ValueError(f"Unsupported phase: {phase}")

    configs_root_path = _resolve_from_repo_root(str(configs_root))
    common_dir = configs_root_path / "common"
    tasks_dir = configs_root_path / "tasks"
    task_dir = tasks_dir / task

    # Required common files
    core_path = common_dir / "core.yaml"
    embeddings_path = common_dir / "embeddings.yaml"
    phase_common_path = common_dir / f"{phase}.yaml"

    # Required task file
    task_path = task_dir / "task.yaml"

    for p in (core_path, embeddings_path, phase_common_path, task_path):
        if not p.is_file():
            raise FileNotFoundError(f"Required config not found: {p}")

    # Optional overrides
    phase_overrides_path = task_dir / f"{phase}_overrides.yaml"
    embeddings_overrides_path = task_dir / "embeddings_overrides.yaml"
    tune_overrides_path = task_dir / "tune_dct3d_overrides.yaml"

    merged: Dict[str, Any] = {}
    merged = _deep_merge(merged, _load_yaml(core_path))
    merged = _deep_merge(merged, _load_yaml(embeddings_path))
    merged = _deep_merge(merged, _load_yaml(phase_common_path))
    merged = _deep_merge(merged, _load_yaml(task_path))

    # Enforce task name consistency if task.yaml defines `task`
    task_in_yaml = merged.get("task")
    if task_in_yaml is None:
        merged["task"] = task
    elif str(task_in_yaml) != str(task):
        raise ValueError(
            f"Task mismatch: folder='{task}' but task.yaml defines task='{task_in_yaml}'."
        )

    # Phase comes from the function argument (not from YAML)
    merged["phase"] = phase

    # Optional per-phase task overrides
    if phase_overrides_path.is_file():
        merged = _deep_merge(merged, _load_yaml(phase_overrides_path))

    # Optional tune-specific overrides (only for tuning)
    if phase == "tune_dct3d" and tune_overrides_path.is_file():
        merged = _deep_merge(merged, _load_yaml(tune_overrides_path))

    # Optional tuned embeddings (NOT included during tune_dct3d by default)
    if phase != "tune_dct3d" and use_embeddings_overrides:
        if embeddings_overrides_path.is_file():
            merged = _deep_merge(merged, _load_yaml(embeddings_overrides_path))

    # Inject run_id / eval_id if provided
    if run_id is not None:
        merged["run_id"] = run_id
    if eval_id is not None:
        merged["eval_id"] = eval_id

    merged["paths"] = _compute_paths(
        merged, configs_root=configs_root_path, task_dir=task_dir
    )

    # Resolve model_init.model_dir to absolute path (if present)
    if isinstance(merged.get("model_init"), dict):
        model_dir = merged["model_init"].get("model_dir", None)
        if model_dir is not None:
            merged["model_init"]["model_dir"] = str(
                _resolve_from_repo_root(str(model_dir))
            )

    # Save merged config for run-based phases only
    if phase != "tune_dct3d":
        run_dir = Path(merged["paths"]["run_dir"])
        run_dir.mkdir(parents=True, exist_ok=True)
        with (run_dir / "config_merged.yaml").open("w", encoding="utf-8") as f:
            yaml.safe_dump(merged, f, sort_keys=False)

    return ExperimentConfig(raw=merged)
