embeddings:
  per_signal_overrides:
    output:
      soft_x_rays-horizontal_cam_lower:
        encoder_name: dct3d
        encoder_kwargs:
          keep_h: 18
          keep_w: 1
          keep_t: 2048
      soft_x_rays-horizontal_cam_upper:
        encoder_name: dct3d
        encoder_kwargs:
          keep_h: 18
          keep_w: 1
          keep_t: 2048
